
openapi: 3.0.0
info:
  title: TTS API estilo ReadSpeaker
  version: 1.0.0
paths:
  /api/tts/synthesize:
    post:
      summary: Convertir texto a voz
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                voice:
                  type: string
                  example: es-LA-SofiaNeural
                speed:
                  type: number
                  example: 1.0
                pitch:
                  type: number
                  example: 1.0
                format:
                  type: string
                  example: mp3
                ssml:
                  type: boolean
                  example: false
                highlight:
                  type: boolean
                  example: true
                returnType:
                  type: string
                  enum: [url, base64, stream]
                  example: url
      responses:
        '200':
          description: Éxito
          content:
            application/json:
              schema:
                type: object
                properties:
                  audioUrl:
                    type: string
                  duration:
                    type: number
                  voice:
                    type: string
                  highlightMap:
                    type: array
                    items:
                      type: object
                      properties:
                        word:
                          type: string
                        start:
                          type: number
                        end:
                          type: number
